name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run GatorGrader with GatorGrade
        if: always()
        run:  |
          pip install gatorgrade
          gatorgrade --config config/gatorgrade.yml





